// Original SunSharp fiction. These are supported comprehension activities,
// not decodability levels or an assessment of oral reading fluency.
// Benchmark references: FDOE B.E.S.T. ELA, literary elements / perspective / theme.
export const READING_STORIES = [
  { id: 'k-hat', grade: 'K', standard: 'ELA.K.R.1.1', skill: 'K.story', passage: 'Sam has a red hat. The hat is on a log. Sam gets the hat and puts it on.', questions: [
    { prompt: 'Where is the hat at first?', choices: ['On a log', 'In a bag', 'On a bed'], answer: 0, explanation: 'The story says the hat is on a log. Then Sam gets it.' },
    { prompt: 'What does Sam do at the end?', choices: ['Gets a bag', 'Puts on the hat', 'Sits on a bed'], answer: 1, explanation: 'At the end, Sam gets the hat and puts it on.' },
  ]},
  { id: 'k-cat', grade: 'K', standard: 'ELA.K.R.1.1', skill: 'K.story', passage: 'A cat sits on a mat. Pam sits by the cat. Pam pats the cat. The cat naps.', questions: [
    { prompt: 'Who sits by the cat?', choices: ['Sam', 'A dog', 'Pam'], answer: 2, explanation: 'The story says Pam sits by the cat.' },
    { prompt: 'What does the cat do last?', choices: ['Naps', 'Runs', 'Jumps'], answer: 0, explanation: 'The last sentence tells us that the cat naps.' },
  ]},
  { id: '1-bridge', grade: '1', standard: 'ELA.1.R.1.1', skill: '1.read', passage: 'Nina made a bridge with blocks. Her toy bus was too wide to cross it. She moved the blocks apart and put a longer block on top. Now the bus could cross. Nina smiled and drove it over again.', questions: [
    { prompt: 'Why did Nina change her bridge?', choices: ['The bus was too wide', 'The blocks were wet', 'The bus was missing'], answer: 0, explanation: 'Nina changes the bridge because her toy bus is too wide to cross it.' },
    { prompt: 'What happened after Nina changed the bridge?', choices: ['She lost the bus', 'The bus could cross', 'The bridge got wet'], answer: 1, explanation: 'After she moves the blocks and adds a longer block, the bus can cross.' },
  ]},
  { id: '1-picnic', grade: '1', standard: 'ELA.1.R.1.1', skill: '1.read', passage: 'Leo and his dad packed a picnic. Rain began as they reached the door. Leo looked at the blanket in his bag. He spread it on the living room floor. They ate their lunch there and listened to the rain.', questions: [
    { prompt: 'Where do Leo and his dad eat their picnic?', choices: ['At a park', 'On a bus', 'In the living room'], answer: 2, explanation: 'Leo spreads the blanket on the living room floor, and they eat there.' },
    { prompt: 'Why do they have their picnic inside?', choices: ['It starts to rain', 'They forget the food', 'The blanket is lost'], answer: 0, explanation: 'Rain begins when they reach the door. Leo finds a way to have the picnic inside.' },
  ]},
  { id: '2-play', grade: '2', standard: 'ELA.2.R.1.3', skill: '2.perspective', passage: 'Mara wanted the biggest speaking part in the class play. Her friend Eli wanted to paint the scenery. Mara thought painting sounded dull until she watched Eli turn a plain sheet into a forest. Eli thought acting looked easy until he heard Mara practice her lines again and again. On show day, Mara thanked Eli for the forest, and Eli cheered when Mara spoke.', questions: [
    { prompt: 'How does Mara feel about painting scenery at first?', choices: ['She thinks it sounds dull', 'She thinks it is the best job', 'She is afraid of it', 'She wants Eli to stop'], answer: 0, explanation: 'The passage says Mara thinks painting sounds dull at first, before she sees Eli make the forest.' },
    { prompt: 'What do Mara and Eli learn about each other’s jobs?', choices: ['Only acting takes work', 'Both jobs take care and effort', 'Painting needs no practice', 'They should cancel the play'], answer: 1, explanation: 'Mara sees Eli transform a sheet. Eli hears Mara practice repeatedly. Each begins to appreciate the other’s work.' },
  ]},
  { id: '2-path', grade: '2', standard: 'ELA.2.R.1.3', skill: '2.perspective', passage: 'Owen hurried along the trail because he wanted to reach the pond. His sister Rosa kept stopping to look at leaves and tiny tracks. Owen sighed each time she stopped. Then Rosa pointed out a line of ants carrying bits of a leaf. Owen crouched beside her. They reached the pond later than planned, but Owen had a new idea for his nature drawing.', questions: [
    { prompt: 'What matters most to Owen at the start?', choices: ['Drawing ants', 'Finding a leaf', 'Reaching the pond', 'Going home'], answer: 2, explanation: 'Owen hurries because he wants to reach the pond. Rosa is interested in details along the way.' },
    { prompt: 'How are Rosa and Owen different at first?', choices: ['Both want to hurry', 'Rosa wants to leave the trail', 'Owen wants to stop more often', 'Rosa notices small things while Owen wants to keep moving'], answer: 3, explanation: 'Rosa stops for leaves and tracks. Owen hurries and sighs when she stops.' },
  ]},
  { id: '3-court', grade: '3', standard: 'ELA.3.R.1.3', skill: '3.perspective', passage: 'The school had one small courtyard. Ada proposed a quiet reading corner. Luis wanted space for a beanbag game. At first, each student thought the other idea would spoil the courtyard. Their teacher asked them to draw where their activities would happen. Ada placed her reading bench under the tree. Luis drew his game near the far wall. When they compared their plans, they noticed an empty path between the two spaces. Ada imagined reading while friends played nearby. Luis liked having somewhere to rest after a game. They submitted one plan together.', questions: [
    { prompt: 'Why do Ada and Luis disagree at first?', choices: ['They want different uses for the same space', 'They cannot find the courtyard', 'Both want a reading bench under the tree', 'Neither wants to use the courtyard'], answer: 0, explanation: 'Ada wants a quiet reading corner, while Luis wants an active game space. Each worries that the other use will spoil the courtyard.' },
    { prompt: 'Which detail shows that their perspectives change?', choices: ['The courtyard is small', 'They imagine enjoying parts of each other’s ideas', 'Their teacher asks them to draw', 'Luis draws near the far wall'], answer: 1, explanation: 'Ada imagines reading near the game, and Luis appreciates a resting place. They see value in each other’s ideas and submit one plan.' },
  ]},
  { id: '3-drum', grade: '3', standard: 'ELA.3.R.1.3', skill: '3.perspective', passage: 'Tess practiced her drum pattern after school. From her room, the steady beat sounded stronger every day. Across the hall, her brother Max was trying to record a poem for class. On his recording, the drum covered the last lines. Max knocked on Tess’s door and explained the problem. Tess had thought he disliked her music. When she heard the recording, she understood. They made a schedule: Max would record first, and then he would listen while Tess practiced her whole song.', questions: [
    { prompt: 'Why does Max ask Tess to stop drumming for a while?', choices: ['He wants to play her drum', 'He dislikes every kind of music', 'The sound covers his poem recording', 'He wants to leave the house'], answer: 2, explanation: 'Max’s recording includes drum sounds that cover his last lines. His concern is recording the poem, not rejecting Tess’s music.' },
    { prompt: 'What helps Tess understand Max’s perspective?', choices: ['Learning a new drum pattern', 'Moving her drum across the room', 'Finishing her song', 'Listening to his recording'], answer: 3, explanation: 'When Tess hears the recording, she understands how her practice affects Max’s work.' },
  ]},
  { id: '4-kite', grade: '4', standard: 'ELA.4.R.1.2', skill: '4.theme', passage: 'Jules arrived at the kite festival carrying a bright kite she had built alone. She had refused her cousin Mina’s offer to help because she wanted all the credit. At the field, the kite spun in circles and fell. Mina suggested making the tail longer, but Jules turned away. After the third crash, Jules studied the tangled string and finally asked Mina to show her idea. Together they added strips of cloth and tested the kite. It rose steadily. When a neighbor praised the design, Jules started to say that she had made it. Then she looked at Mina holding the spool and said they had improved it together.', questions: [
    { prompt: 'Which theme develops through Jules’s actions?', choices: ['Accepting help can improve your work', 'Winning matters more than learning', 'Good ideas never need changes', 'Working alone always works best'], answer: 0, explanation: 'Jules first rejects help. After accepting Mina’s suggestion, the kite flies and Jules shares the credit. Those changes develop the theme.' },
    { prompt: 'Which detail best shows that Jules has learned this lesson?', choices: ['She brings a bright kite to the festival', 'She gives Mina credit for improving the kite', 'The string gets tangled after a crash', 'A neighbor walks over to the kite'], answer: 1, explanation: 'Sharing credit shows more than a successful kite: Jules now values Mina’s contribution instead of wanting all the credit herself.' },
  ]},
  { id: '4-bench', grade: '4', standard: 'ELA.4.R.1.2', skill: '4.theme', passage: 'When the neighborhood announced a cleanup morning, Ravi promised to help repair the park bench. On Saturday, a friend invited him to try a new video game at the same time. Ravi nearly accepted. Then he remembered Mrs. Chen saying that she needed the bench to rest during her walks. He told his friend he would come later and went to the park. The repair took longer than he expected. Ravi sanded one rough board while an adult secured the loose parts. That afternoon, he saw Mrs. Chen sitting comfortably on the bench. He still wanted to play the game, but he was glad he had kept his promise.', questions: [
    { prompt: 'Which theme is supported by Ravi’s choice?', choices: ['Games are never worth playing', 'Repairs should always be done alone', 'Keeping a promise can help others', 'Plans should never change for any reason'], answer: 2, explanation: 'Ravi chooses to honor his promise and later sees how the repaired bench helps Mrs. Chen. The story connects responsibility with helping another person.' },
    { prompt: 'How does the ending develop the theme?', choices: ['It explains the rules of the game', 'It says the repair was easy', 'It shows Ravi forgetting his promise', 'It shows Ravi seeing the benefit of keeping his promise'], answer: 3, explanation: 'Seeing Mrs. Chen rest on the bench helps Ravi understand the value of the choice he made.' },
  ]},
  { id: '5-mural', grade: '5', standard: 'ELA.5.R.1.3', skill: '5.perspective', passage: 'When the town planned a mural, Elena submitted a sketch of its newest buildings. She believed progress meant showing what was modern. At a planning meeting, an older resident described the small ferry that had once connected the town’s two shores. Elena had never noticed the faded ferry sign beside the bridge. She visited it the next day and found scratches where years of travelers had rested their bicycles. Back at her desk, she drew the ferry beneath a transparent outline of the current bridge. She kept the new buildings, too. When she presented the revision, she explained that a town’s future made more sense when people could also see how it had arrived there. The old sketch lay beside the new one, but she no longer wanted to use it.', questions: [
    { prompt: 'How does Elena’s perspective change?', choices: ['She comes to value both the town’s history and its new development', 'She decides all new buildings should be removed', 'She thinks history has nothing to do with the mural', 'She loses interest in making a mural'], answer: 0, explanation: 'At first Elena includes only modern buildings. Her revised sketch combines the old ferry, the bridge, and new buildings, showing that she now values connections between past and present.' },
    { prompt: 'How does the author develop this change?', choices: ['By listing every building in town', 'By showing Elena listen, investigate, and revise her design', 'By saying all the residents agree with Elena', 'By describing only the colors of the mural'], answer: 1, explanation: 'The meeting introduces another viewpoint. Elena then visits the sign and changes her sketch. That sequence lets readers see her perspective develop through actions.' },
  ]},
  { id: '5-test', grade: '5', standard: 'ELA.5.R.1.3', skill: '5.perspective', passage: 'Marcus was certain his team’s paper tower would hold the most coins. He had spent an evening folding its wide base and wanted to skip the final test. A teammate, Noor, asked to test a smaller model first. Marcus thought the test would waste their remaining time. During the trial, one folded seam bent and the model leaned. Marcus reached to straighten it, then stopped and asked Noor to note where the bend had started. They used a spare sheet to strengthen the matching seam on the full tower. Before the class demonstration, Marcus requested one more test himself. He still hoped their tower would do well, but now he wanted evidence that the design could support that hope.', questions: [
    { prompt: 'What change in Marcus’s perspective does the final sentence reveal?', choices: ['He no longer cares about the project', 'He thinks Noor should work alone', 'He now values testing instead of relying only on confidence', 'He believes every test is a waste of time'], answer: 2, explanation: 'Marcus begins by wanting to skip testing. After the model bends, he asks for another test and wants evidence to support his confidence.' },
    { prompt: 'Which action most clearly demonstrates his changed perspective?', choices: ['Folding a wide base the night before', 'Hoping the tower holds many coins', 'Working with a teammate', 'Requesting another test before the demonstration'], answer: 3, explanation: 'His request reverses his earlier wish to skip the test. It directly shows that he has come to value evidence.' },
  ]},
] as const;
