import type { ScienceObservation } from '../science-observation';
import type { Grade } from '../types';
type ObservationActivity = { id: string; grade: Grade; observation: ScienceObservation; questions: { prompt: string; choices: string[]; answer: number; explanation: string }[] };
// Original illustrative classroom records, not measurements from a real study.
// These activities practice observing and using evidence, not full inquiry mastery.
export const SCIENCE_OBSERVATIONS: ObservationActivity[] = [
  {id:'k-balls',grade:'K',observation:{title:'Look at the balls',context:'Look closely. Which things are the same? Which thing is different?',format:'objects',columns:['Color'],rows:[{label:'A',values:['Red'],symbol:'red-ball'},{label:'B',values:['Red'],symbol:'red-ball'},{label:'C',values:['Blue'],symbol:'blue-ball'}]},questions:[
    {prompt:'Which ball has a different color from the other two?',choices:['A','B','C'],answer:2,explanation:'A and B are red. C is blue, so C has a different color.'},
    {prompt:'Which two balls have the same color?',choices:['A and B','A and C','B and C'],answer:0,explanation:'A and B are both red. We can compare things by looking at their colors.'},
  ]},
  {id:'1-weather',grade:'1',observation:{title:'Our weather week',context:'A class looked outside at noon each day and made this picture record.',format:'weather',columns:['Weather'],rows:[{label:'Monday',values:['Sunny'],symbol:'sun'},{label:'Tuesday',values:['Rainy'],symbol:'rain'},{label:'Wednesday',values:['Rainy'],symbol:'rain'},{label:'Thursday',values:['Sunny'],symbol:'sun'},{label:'Friday',values:['Rainy'],symbol:'rain'}]},questions:[
    {prompt:'How many days in this record were rainy at noon?',choices:['2','3','5'],answer:1,explanation:'Tuesday, Wednesday, and Friday show rain. That makes 3 rainy observations.'},
    {prompt:'Which two days show sunny weather at noon?',choices:['Tuesday and Friday','Wednesday and Thursday','Monday and Thursday'],answer:2,explanation:'The sunny pictures are on Monday and Thursday. The record only tells us about the time the class looked.'},
  ]},
  {id:'2-light',grade:'2',observation:{title:'What happened to the light?',context:'In this sample investigation, a class used the same flashlight at the same distance. They changed the material in front of it.',format:'table',columns:['Light seen on screen'],rows:[{label:'Clear plastic',values:['Bright light']},{label:'Wax paper',values:['Dim light']},{label:'Cardboard',values:['No light']}]},questions:[
    {prompt:'Which material let the most light through in these observations?',choices:['Clear plastic','Wax paper','Cardboard','They all let through the same amount'],answer:0,explanation:'The clear plastic produced bright light on the screen. Wax paper produced dim light, and cardboard produced none.'},
    {prompt:'What did the class change between these tests?',choices:['The distance from the flashlight','The material in front of the flashlight','The time of day','The screen size'],answer:1,explanation:'The notes say the flashlight and distance stayed the same. The material was the thing that changed.'},
  ]},
  {id:'3-ramps',grade:'3',observation:{title:'A toy car investigation',context:'These sample results use the same car and floor. The car was released without a push from ramps of three heights.',format:'bars',columns:['Distance traveled'],unit:'cm',scaleMax:100,rows:[{label:'Low ramp',values:['40 cm'],amount:40},{label:'Middle ramp',values:['65 cm'],amount:65},{label:'High ramp',values:['90 cm'],amount:90}]},questions:[
    {prompt:'Which pattern is shown in these trials?',choices:['Higher ramps led to shorter distances','All distances were equal','Higher ramps led to longer distances','The low ramp sent the car farthest'],answer:2,explanation:'The recorded distance increases from 40 to 65 to 90 cm as ramp height increases. This describes these trials, not every possible car and ramp.'},
    {prompt:'Which detail helps make this a fair comparison of ramp heights?',choices:['The ramps have different heights','The distances are different','The bars have labels','The same car and floor were used'],answer:3,explanation:'Keeping the car and floor the same helps the class compare the effect of changing ramp height.'},
  ]},
  {id:'4-cups',grade:'4',observation:{title:'Comparing cup covers',context:'An adult prepared equal amounts of warm water in identical cups. Each started at 50°C. The cups stayed in the same room for 10 minutes. Only the wrapping material changed. These are sample results.',format:'table',columns:['Start','After 10 min'],rows:[{label:'Paper wrap',values:['50°C','40°C']},{label:'Cloth wrap',values:['50°C','44°C']},{label:'Foam wrap',values:['50°C','47°C']}]},questions:[
    {prompt:'Which conclusion is best supported by the results?',choices:['The foam-wrapped cup had the smallest temperature drop','The paper-wrapped cup stayed warmest','All cups ended at the same temperature','Cloth made the water hotter than it started'],answer:0,explanation:'The foam-wrapped cup changed from 50°C to 47°C, a drop of 3°C. The cloth and paper cups dropped 6°C and 10°C.'},
    {prompt:'Why did all cups start with the same amount and temperature of water?',choices:['To make every final temperature identical','To make the comparison of wrapping materials fairer','To make the experiment finish instantly','To prove that no heat could escape'],answer:1,explanation:'Keeping the starting conditions alike helps the class investigate wrapping material instead of differences in the water at the start.'},
  ]},
  {id:'5-surfaces',grade:'5',observation:{title:'Does the surface matter?',context:'A team released the same toy car from the same ramp height without pushing it. They measured the distance after the car reached each surface. Each surface was tested three times. These are sample results.',format:'table',columns:['Trial 1','Trial 2','Trial 3'],rows:[{label:'Carpet',values:['31 cm','33 cm','32 cm']},{label:'Cardboard',values:['54 cm','57 cm','55 cm']},{label:'Tile',values:['92 cm','96 cm','94 cm']}]},questions:[
    {prompt:'Which claim is supported by all three trials?',choices:['The car always moved at the same speed','The ramp height caused every difference','The car traveled farthest on tile in these tests','All three surfaces produced equal distances'],answer:2,explanation:'Every tile distance is greater than every cardboard or carpet distance. These results support a claim about distance in these tests; speed was not measured.'},
    {prompt:'Why are repeated trials useful here?',choices:['They guarantee that measurements cannot be wrong','They replace the need to keep the ramp height the same','They prove the result for every kind of toy car','They show whether a pattern is consistent across attempts'],answer:3,explanation:'The distances vary a little, but the same surface pattern appears in every trial. Repeating tests helps evaluate consistency without guaranteeing perfect results.'},
  ]},
];
