import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import { redirect } from 'next/navigation';
import { getSessionProfile } from '@/lib/auth';
import { isBillingOn } from '@/lib/settings';
import { MarketingNav } from '@/components/marketing/MarketingNav';
import { TRIAL_DAYS } from '@/lib/billing';
export const metadata: Metadata = { alternates: { canonical: '/' } };
const worlds=[['Garden','Grow something wonderful.','/images/garden/garden-bed.webp'],['Railway','Build a train of your own.','/images/train/engine.webp'],['Dinosaurs','Make a prehistoric world.','/images/dinosaurs/triceratops.webp'],['Bakery','Fill your shelf with favorites.','/images/bakery/cupcake.webp']];
export default async function Home(){const {profile}=await getSessionProfile();if(profile)redirect(profile.role==='parent'?'/parent':'/home');const billingOn=await isBillingOn();return <><MarketingNav/><main className="mx-auto w-full min-w-0 max-w-6xl px-5"><section className="marketing-hero"><div><span className="eyebrow text-teal-800">Little moments. Lasting discoveries.</span><h1>Big curiosity.<br/><em>Brighter days.</em></h1><p>A little math. A new story. A world to discover. Turn everyday practice into something your child looks forward to.</p><div className="mt-7 flex flex-wrap items-center gap-4"><Link href="/signup" className="marketing-cta">{billingOn?`Start ${TRIAL_DAYS}-day free trial`:'Get started free'} <span aria-hidden="true">↗</span></Link><Link href="/kids" className="inline-flex min-h-12 items-center px-3 font-bold text-teal-800">Kid login →</Link></div><p className="mt-5 !text-sm">Built for K–5 · Read-aloud guidance · No ads</p></div><div className="marketing-hero-visual"><Image src="/images/ui/discovery.webp" alt="A rocket, storybook, sun, and colorful learning blocks" fill unoptimized loading="eager" className="object-contain p-4"/><span>A little practice opens a whole new world.</span></div></section>
<section className="marketing-section border-y border-[#e3e9e4]"><p className="eyebrow text-teal-800">Made for their next discovery</p><h2 className="mt-3">Practice first. Confidence follows.</h2><p className="section-intro">Short practice quizzes in math, reading, and science, with more subjects to explore. Step-by-step lessons help when a new idea needs a little extra time.</p><div className="marketing-steps">{[['math','Math','Build confidence with numbers, shapes, and problem solving.'],['reading','Reading','Explore sounds, words, and stories worth getting lost in.'],['science','Science','Ask questions and discover how the world works.']].map(([id,title,copy])=><article key={id} className={`marketing-step marketing-subject subject-${id}`}><div className="subject-art relative mb-5 h-32"><Image src={`/images/ui/${id}.webp`} alt="" fill unoptimized className="object-contain"/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="marketing-section"><p className="eyebrow text-teal-800">Their effort. Their little world.</p><h2 className="mt-3">A reason to come back smiling.</h2><p className="section-intro">Practice grows flowers and earns tokens. Kids choose what to collect, and their creations stay saved. Mistakes count as effort, too.</p><div className="reward-showcase">{worlds.map(([name,copy,src])=><Link key={name} href="/signup"><div className="reward-showcase-art"><Image src={src} alt="" fill unoptimized className={name==='Garden'?'object-cover':'object-contain p-4'}/></div><h3>{name}</h3><p>{copy}</p></Link>)}</div></section>
<section className="marketing-section border-t border-[#e3e9e4]"><p className="eyebrow text-teal-800">Simple for the whole family</p><h2 className="mt-3">You set it up. They take it from there.</h2><div className="marketing-steps">{[['01','Make a family account','Create a child login with a username and PIN. You manage the account.'],['02','Find their starting point','Choose a grade and start a short practice quiz. Spoken guidance is a tap away.'],['03','See the progress','Follow practice, subjects, and learning goals from your parent dashboard.']].map(([n,title,copy])=><article key={n} className="marketing-step"><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="my-10 rounded-[28px] bg-[#e5efe3] p-8 text-center sm:p-14"><h2 className="text-3xl font-extrabold tracking-tight">Let’s make room for curiosity.</h2><p className="mx-auto mt-3 max-w-xl text-slate-600">A welcoming place to practice, explore, and grow.</p><Link href="/signup" className="marketing-cta mt-6">{billingOn?'Try SunSharp':'Start learning free'} ↗</Link><Link href="/pricing" className="ml-4 inline-flex min-h-12 items-center font-bold text-teal-800">View plans →</Link></section></main></>;}
