import { notFound } from 'next/navigation';
import { LearningRewards } from '@/components/LearningRewards';
import { gardenProgress } from '@/lib/garden';
import type { TrainState } from '@/lib/train';
import type { Grade } from '@/lib/types';
export default async function Page({searchParams}:{searchParams:Promise<{grade?:string;theme?:string;tokens?:string}>}){
 if(process.env.NODE_ENV==='production')notFound();const {grade='K',theme='train',tokens='30'}=await searchParams;if(!['K','1','2','3','4','5'].includes(grade))notFound();
 const state:TrainState={activeEngine:"engine",engines:[],engineCatalog:[{id:"engine",name:"Classic steam engine",price:0,sort:0},{id:"passenger-engine",name:"Passenger engine",price:15,sort:1},{id:"bullet-engine",name:"Bullet train engine",price:25,sort:2},{id:"diesel-engine",name:"Cargo diesel engine",price:20,sort:3},{id:"j-steam-engine",name:"Green J steam engine",price:15,sort:4}],theme:theme==='bakery'?'bakery':'train',earned:Math.min(500,Math.max(0,Number(tokens)||0)),spent:0,balance:Math.min(500,Math.max(0,Number(tokens)||0)),treats:[],bakeryCatalog:[{id:'donut',name:'Sprinkle donut',price:5,sort:1},{id:'cupcake',name:'Swirl cupcake',price:8,sort:2},{id:'cakepop',name:'Chocolate cake pop',price:10,sort:3},{id:'cookie',name:'Chocolate chip cookie',price:5,sort:4},{id:'croissant',name:'Golden croissant',price:8,sort:5},{id:'macarons',name:'Macaron stack',price:12,sort:6}],cars:[],dinosaurs:[],dinosaurCatalog:[{id:'triceratops',name:'Triceratops',price:5,sort:1},{id:'stegosaurus',name:'Stegosaurus',price:8,sort:2},{id:'brachiosaurus',name:'Brachiosaurus',price:10,sort:3},{id:'parasaurolophus',name:'Parasaurolophus',price:10,sort:4},{id:'ankylosaurus',name:'Ankylosaurus',price:12,sort:5},{id:'tyrannosaurus',name:'Tyrannosaurus',price:15,sort:6}],catalog:[{id:'passenger',name:'Sunny passenger car',price:5,sort:1},{id:'cargo',name:'Cargo car',price:8,sort:2},{id:'aquarium',name:'Aquarium car',price:10,sort:3},{id:'garden',name:'Garden car',price:10,sort:4},{id:'observatory',name:'Stargazer car',price:12,sort:5},{id:'caboose',name:'Cherry caboose',price:15,sort:6},{id:'dining',name:'Dining car',price:10,sort:7},{id:'sleeper',name:'Sleeper car',price:12,sort:8},{id:'bullet-coach',name:'Bullet train coach',price:12,sort:9},{id:'tanker',name:'Tanker car',price:8,sort:10},{id:'log-flatcar',name:'Log flatcar',price:8,sort:11}]};
 return <main data-grade={grade} className="grade-home mx-auto w-full min-w-0 max-w-3xl px-4 py-6"><p className="text-sm text-slate-600">Rewards preview · sample tokens · no purchases saved</p><LearningRewards grade={grade as Grade} initialGarden={gardenProgress(30,0)} initialTrain={state} full preview/></main>;
}
