'use client';
import { useRef, useState } from 'react';
import Link from 'next/link';
import { buyTrainCar, moveTrainCar } from '@/app/actions/train';
import { TrainArt } from '@/components/TrainArt';
import { RecordedNarration } from '@/components/LessonNarration';
import { HOME_NARRATION } from '@/lib/home-narration';
import { experienceFor } from '@/lib/grade-experience';
import type { Grade } from '@/lib/types';
import type { TrainState } from '@/lib/train';
export function LearningTrain({initial,grade,full=false,preview=false,onChange}:{initial:TrainState;grade:Grade|null;full?:boolean;preview?:boolean;onChange?:(state:TrainState)=>void}) {
 const [state,setState]=useState(initial);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [selected,setSelected]=useState<string|null>(null);
 function update(next:TrainState){setState(next);onChange?.(next);}
 const requests=useRef<Record<string,string>>({});const experience=experienceFor(grade);const strip=useRef<HTMLDivElement>(null);
 async function buy(car:string){if(busy)return;setBusy(true);setMessage('');const request=requests.current[car]??crypto.randomUUID();requests.current[car]=request;
  try{const item=state.catalog.find(c=>c.id===car)!;const next=preview?{...state,balance:state.balance-item.price,spent:state.spent+item.price,cars:[...state.cars,{id:request,carId:item.id,position:state.cars.length+1}]}:await buyTrainCar(car,request);update(next);delete requests.current[car];setSelected(request);setMessage(`${item.name} added to your train!`);requestAnimationFrame(()=>strip.current?.scrollTo({left:strip.current.scrollWidth,behavior:'auto'}));}
  catch{setMessage('Your purchase could not be confirmed. Tap the same buy button to retry safely.');}finally{setBusy(false);}}
 async function move(direction:number){if(!selected||busy)return;setBusy(true);setMessage('');try{if(preview){const cars=[...state.cars];const i=cars.findIndex(c=>c.id===selected);[cars[i],cars[i+direction]]=[cars[i+direction],cars[i]];update({...state,cars});}else update(await moveTrainCar(selected,direction));setMessage('Your train order is saved.');}catch{setMessage('That move did not save. Please try again.');}finally{setBusy(false);}}
 const selectedIndex=state.cars.findIndex(c=>c.id===selected);
 return <section aria-label="My learning train" className="mt-5 min-w-0 overflow-hidden rounded-3xl border border-slate-200 bg-[#fffdf6] shadow-sm">
  <div className="flex items-start justify-between gap-3 p-5 sm:p-7"><div><p className="text-xs font-extrabold uppercase tracking-widest text-sky-800">Your learning railway</p><h2 className="mt-1 text-3xl font-bold text-slate-800">All aboard!</h2><p className="mt-2 text-slate-600">{state.cars.length?`${state.cars.length} ${state.cars.length===1?'car':'cars'} in your train`:'Your free engine is ready.'}</p></div><div className="shrink-0 rounded-2xl border border-amber-200 bg-amber-100 px-4 py-3 text-center text-amber-950"><strong className="block text-3xl tabular-nums" aria-label={`${state.balance} tokens`}>{state.balance}</strong><span className="text-sm font-bold">tokens</span></div></div>
  <div style={{background:experience.sky}} className="relative border-y border-slate-200 pt-6"><div aria-hidden="true" className="absolute bottom-[52px] h-3 w-full border-y-2 sm:bottom-[58px] border-slate-500 bg-slate-300"/><div ref={strip} tabIndex={0} role="region" aria-label="Your train. Scroll sideways to see every car." className="relative flex min-w-0 gap-1 overflow-x-auto px-4 pb-3 focus-visible:outline-2 focus-visible:outline-sky-700">
   <div className="w-44 shrink-0 sm:w-52"><TrainArt kind="engine" friendly={experience.earlyReader}/><p className="rounded-full bg-white/95 px-2 py-1 text-center text-xs font-bold text-slate-700">Your engine · Free</p></div>
   {state.cars.map((car,i)=><button key={car.id} disabled={!full||busy} aria-pressed={selected===car.id} aria-label={`Select ${state.catalog.find(c=>c.id===car.carId)?.name}, car ${i+1}`} onClick={()=>setSelected(car.id)} className={`w-44 shrink-0 rounded-xl border-2 p-1 sm:w-52 ${selected===car.id?'border-sky-700 bg-white/60':'border-transparent'}`}><TrainArt kind={car.carId}/><span className="block rounded-full bg-white/95 px-2 py-1 text-center text-xs font-bold text-slate-700">Car {i+1}</span></button>)}
   {!state.cars.length&&<div className="my-6 grid w-40 shrink-0 place-items-center rounded-2xl border-2 border-dashed border-slate-400 bg-white/60 p-4 text-center font-bold text-slate-600">Your first car goes here</div>}
  </div></div>
  <div className="p-5 sm:px-7"><div className="flex items-center gap-3"><p className="flex-1 text-base leading-relaxed text-slate-700">Try a question: <strong>1 token.</strong><br/>Finish a lesson: <strong>5 tokens.</strong><br/><span className="text-sm">Mistakes count, too. Your train stays when you take a break.</span></p><RecordedNarration id="home:train" text={HOME_NARRATION['home:train']} label="Hear how my train works"/></div>
   {full&&state.cars.length>1&&<p className="mt-4 text-sm text-slate-600">Swipe to see your train. Tap a car to change its place.</p>}
   {full&&selectedIndex>=0&&<div className="mt-3 flex flex-wrap gap-2"><button disabled={busy||selectedIndex===0} onClick={()=>move(-1)} className="min-h-12 rounded-xl bg-sky-100 px-4 py-3 font-bold text-sky-900 disabled:opacity-40">← Toward engine</button><button disabled={busy||selectedIndex===state.cars.length-1} onClick={()=>move(1)} className="min-h-12 rounded-xl bg-sky-100 px-4 py-3 font-bold text-sky-900 disabled:opacity-40">Toward back →</button></div>}
   {message&&<p role="status" className="mt-4 rounded-xl bg-sky-50 p-3 font-bold text-sky-900">{message}</p>}
   {!full?<Link href="/train" className="mt-5 inline-flex min-h-12 items-center rounded-xl bg-sky-800 px-5 py-3 font-bold text-white">Build my train →</Link>:<><h3 className="mt-7 text-2xl font-bold text-slate-800">Choose your next car</h3><p className="mt-1 text-slate-600">Buy a car and it joins your train. You can collect more than one.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{state.catalog.map(car=><div key={car.id} className="flex min-w-0 flex-col rounded-2xl border border-slate-200 bg-white p-3"><TrainArt kind={car.id}/><h4 className="flex-1 text-base font-bold text-slate-800">{car.name}</h4><p className="mt-2 font-bold text-amber-900">{car.price} tokens</p><button disabled={busy||state.balance<car.price} onClick={()=>buy(car.id)} aria-label={`Buy ${car.name} for ${car.price} tokens`} className="mt-3 min-h-12 rounded-xl bg-sky-800 px-2 py-3 font-bold text-white disabled:bg-slate-100 disabled:text-slate-500">{state.balance<car.price?`${car.price-state.balance} more to go`:'Buy car'}</button></div>)}</div><Link href="/practice/daily" className="mt-5 inline-flex min-h-12 items-center rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">Practice for more tokens →</Link></>}
  </div>
 </section>;
}
