-- GENERATED from scripts/reading-detail-content.mjs. Preserve existing questions and history.
-- Run node scripts/validate-reading-detail.mjs before publishing.
-- Three grade-three scaffolds; partial supporting-details practice, not benchmark mastery.
with incoming as (
 select * from jsonb_to_recordset($reading_detail$[
  {"subject_id":"reading","grade":"3","difficulty":1,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The classroom book cart has three shelves. Animal books go on the top shelf. Poetry books go on the middle shelf. The bottom shelf holds books about sports.\" Which detail tells where to find poetry books?","explanation":"The sentence about poetry names the middle shelf. The other shelves hold different kinds of books.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["They are on the middle shelf.","They are on the top shelf.","They are on the bottom shelf.","They are beside the window."],"answer_index":0},
  {"subject_id":"reading","grade":"3","difficulty":1,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The garden club plants beans and peas. Members put a wooden label beside each row. The labels show which seeds are in that row.\" What do the labels tell the garden club?","explanation":"The passage directly says that the labels identify the seeds in each row.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["How tall each plant will grow.","How many leaves each plant has.","When every flower will open.","Which seeds are in each row."],"answer_index":3},
  {"subject_id":"reading","grade":"3","difficulty":1,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"A class keeps a rain record. After each rainy day, an adult reads the water level in a rain gauge. The class writes the amount on a chart.\" Where does the class write the amount of rain?","explanation":"The chart is where the class records the amount. The gauge is used to measure it.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["On a leaf.","On the playground gate.","On a chart.","On the rain gauge."],"answer_index":2},
  {"subject_id":"reading","grade":"3","difficulty":1,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The art room has a repair box. It holds tape, spare crayons, and glue sticks. Students use the tape to mend torn paper.\" Which item do students use to mend torn paper?","explanation":"The passage names tape as the material used to mend torn paper.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["A ruler.","Tape.","Spare crayons.","A paintbrush."],"answer_index":1},
  {"subject_id":"reading","grade":"3","difficulty":1,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The museum bus stops by the school gate. A teacher checks the passenger list before children climb aboard. Backpacks go under the seats so the aisle stays clear.\" Where do the backpacks go?","explanation":"The passage says backpacks go under the seats. Keeping the aisle clear explains why.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["Under the seats.","In the aisle.","Beside the school gate.","On the bus steps."],"answer_index":0},
  {"subject_id":"reading","grade":"3","difficulty":1,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The puppet club puts on a show each Friday. A blue curtain hides the performers. Two children hold puppets above the curtain while another child reads the story.\" What hides the performers?","explanation":"The sentence names a blue curtain as the thing that hides the performers.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["A tall bookshelf.","A row of chairs.","A painted umbrella.","A blue curtain."],"answer_index":3},
  {"subject_id":"reading","grade":"3","difficulty":1,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"A volunteer delivers fruit to the classroom. Apples arrive in a green basket. Bananas arrive in a yellow basket. Empty baskets are returned to the kitchen.\" Which basket holds apples?","explanation":"The passage gives a different basket color for each fruit. Apples go in green.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["A blue basket.","A red basket.","The green basket.","The yellow basket."],"answer_index":2},
  {"subject_id":"reading","grade":"3","difficulty":1,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"A park map uses small pictures. A table picture marks a picnic area. A water-drop picture marks a drinking fountain. A shoe picture marks a walking trail.\" Which picture marks a drinking fountain?","explanation":"The water-drop picture is the map symbol for a drinking fountain.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["A tree picture.","A water-drop picture.","A table picture.","A shoe picture."],"answer_index":1},
  {"subject_id":"reading","grade":"3","difficulty":2,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The building club used to lose small tools. Now each tool hangs above an outline of its shape. An empty outline shows that a tool has not been returned. Members check the outlines before leaving.\" How do the outlines help members notice a missing tool?","explanation":"An empty shape is visible when its tool is missing. The passage does not say the outlines identify who used it.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["An empty outline shows where a tool belongs.","The outlines make tools heavier.","Each outline tells who last used a tool.","The outlines stop members from using tools."],"answer_index":0},
  {"subject_id":"reading","grade":"3","difficulty":2,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The reading corner is beside a busy hallway. The class moves it to the far wall and places a thick rug beneath the chairs. After the move, readers hear fewer footsteps from the hall.\" Which detail shows that moving the reading corner helped?","explanation":"Hearing fewer footsteps is the result that shows the reading space became quieter. The other details describe the setting or changes, not the result.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["The corner used to be beside a hallway.","The chairs stand on a rug.","The hallway is used during school.","Readers hear fewer hallway footsteps."],"answer_index":3},
  {"subject_id":"reading","grade":"3","difficulty":2,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The class has one watering can. At first, several children water the same plant while others get none. A chart now assigns one plant to each helper. Helpers mark the chart after watering.\" Why does marking the chart help?","explanation":"A mark records completed watering, so helpers can avoid repeating the same job while missing another plant.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["It tells helpers to water every plant twice.","It changes the amount the can can hold.","It shows which plants have already been watered.","It makes every plant grow flowers."],"answer_index":2},
  {"subject_id":"reading","grade":"3","difficulty":2,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The toy-car club compares two ramps. Both ramps use the same toy car and start at the same height. One ramp has a smooth surface, and the other has a rough surface. Members record how far the car travels from each ramp.\" Which detail shows that surface is the difference being compared?","explanation":"This sentence names the feature that changes. The same car and height keep other features alike.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["Members write down distances.","One surface is smooth and the other is rough.","Both ramps start at the same height.","The club uses a toy car."],"answer_index":1},
  {"subject_id":"reading","grade":"3","difficulty":2,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"New readers sometimes cannot find books by topic. The library adds a picture beside each topic word. A paw print appears beside Animals, and a planet appears beside Space. Children can use the picture even if the word is unfamiliar.\" How do the pictures help new readers?","explanation":"The pictures give topic clues without requiring children to read each topic word.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["They give clues to topics before readers know every word.","They tell how every story ends.","They replace all the books in the library.","They show which books are the longest."],"answer_index":0},
  {"subject_id":"reading","grade":"3","difficulty":2,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"A class makes a board game. Its first direction sheet has only words. Test players keep asking where to put their pieces. The class adds a drawing of the starting spaces. On the next test, players place their pieces without asking.\" Which detail shows that the drawing made the directions clearer?","explanation":"The new result directly addresses the earlier problem: players now know where their pieces start.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["The game has a direction sheet.","The first sheet has only words.","The class makes a board game.","Players place their pieces without asking."],"answer_index":3},
  {"subject_id":"reading","grade":"3","difficulty":2,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"At the craft table, scraps used to pile up together. The class adds separate bins for paper and cloth. Each bin has a sample attached to its front. Students compare a scrap with the samples before choosing a bin.\" Why are samples attached to the bins?","explanation":"The last sentence explains how students use the samples to choose the right bin.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["They show how much each bin weighs.","They make paper and cloth the same material.","Students can compare scraps with them when sorting.","They tell students to throw away every scrap."],"answer_index":2},
  {"subject_id":"reading","grade":"3","difficulty":2,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"At field day, children first line up at one water table. The line reaches across a running path. Teachers add a second table away from the path. The two shorter lines leave the path open.\" Which detail explains why the second table was useful?","explanation":"Keeping the path open solves the problem described earlier: the long line crossed it.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["The first table is still there.","The shorter lines leave the running path open.","Field day takes place at school.","Children drink water at a table."],"answer_index":1},
  {"subject_id":"reading","grade":"3","difficulty":3,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The school garden is designed so more people can take part. Wide paths leave room for people using wheelchairs. Some planting boxes are raised so gardeners can reach them while sitting. The boxes are painted blue, and marigolds grow near the entrance.\" Which pair of details best supports the idea that more people can garden here?","explanation":"Wide paths provide room to move, and raised boxes make plants reachable while sitting. The color and flower name do not explain access.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["Wide paths and raised planting boxes.","Blue boxes and flowers at the entrance.","Marigolds and the color of the boxes.","The entrance and the name of the flowers."],"answer_index":0},
  {"subject_id":"reading","grade":"3","difficulty":3,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The class plans a party with less throwaway waste. Families lend washable cups, and students make decorations from saved paper. The party is on Tuesday in a room with yellow walls. A music club performs two songs.\" Which detail best supports the idea that the party creates less throwaway waste?","explanation":"Washable cups can be used again rather than thrown away after the party. The date, walls, and music do not explain waste reduction.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["The party is on Tuesday.","The room has yellow walls.","The music club performs two songs.","Families lend washable cups."],"answer_index":3},
  {"subject_id":"reading","grade":"3","difficulty":3,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The weather club makes its records easy to compare. Members read the same thermometer at the same time each school day. They write every reading in degrees Celsius. Their notebook has a green cover, and six students belong to the club.\" Why do the same reading time and temperature unit support the club’s goal?","explanation":"Using the same procedure and unit makes comparisons clearer. It does not make temperatures equal or prove a pattern for a whole year.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["They explain why the cover is green.","They show that six readings are enough for a year.","They keep the way readings are recorded consistent.","They prove every day has the same weather."],"answer_index":2},
  {"subject_id":"reading","grade":"3","difficulty":3,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The class museum lets visitors explore models in different ways. A model bridge has large handles for lifting its parts. Labels include raised letters that visitors can feel. The display table is brown, and a poster lists the museum’s opening date.\" Which pair of details supports the idea that visitors can explore models in different ways?","explanation":"Handles allow visitors to move parts, while raised letters can be explored by touch. The other details do not describe ways to explore.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["The opening date and the table color.","Large handles and raised letters.","A brown table and an opening date.","A poster and the color brown."],"answer_index":1},
  {"subject_id":"reading","grade":"3","difficulty":3,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The reading-buddy club helps younger children take part in story time. Older buddies pause to let children describe the pictures. They also invite children to choose the next book. The club meets in Room 8 on Thursdays, and the book basket is red.\" Which detail best supports the idea that younger children take an active part?","explanation":"Choosing a book gives children a decision to make. The room, day, and basket color do not show participation.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["Children are invited to choose the next book.","The club meets on Thursdays.","The book basket is red.","The room is numbered 8."],"answer_index":0},
  {"subject_id":"reading","grade":"3","difficulty":3,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The school improves a crowded walkway. Staff move a storage cart away from the door and paint arrows that show where each line should go. The hallway has three windows. A display of leaf drawings hangs beside the door.\" Which details best support the idea that the changes help people move through the walkway?","explanation":"Moving the cart clears space, and arrows guide the lines. The windows and drawings do not explain the improvement to movement.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["Three windows and leaf drawings.","Leaf drawings and a nearby door.","The window count and the display location.","Moving the cart and painting direction arrows."],"answer_index":3},
  {"subject_id":"reading","grade":"3","difficulty":3,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"The class wants each reader to have an equal say in choosing a book. Every student receives one voting slip. Students mark slips privately, and a teacher counts every slip once. The three book covers are displayed on a purple board.\" Which detail most directly supports an equal say for each reader?","explanation":"One slip for every student gives each student the same number of votes. The display details do not show equal voting.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["The board is purple.","The covers are displayed together.","Every student receives one voting slip.","There are three book covers."],"answer_index":2},
  {"subject_id":"reading","grade":"3","difficulty":3,"skill":"3.detail","standard":"ELA.3.R.2.2","prompt":"Read: \"A neighborhood repair club helps families keep using broken items. Volunteers mend torn bags and replace loose toy wheels. The club meets on Saturday beside the library. Its sign has orange letters and a picture of a toolbox.\" How do the examples of bags and toy wheels support the main idea?","explanation":"Mending a bag or fixing a wheel can make an item usable again. The examples support reuse, not buying replacements.","xp":10,"kind":"mcq","payload":null,"answer":null,"choices":["They show that the library sells new bags.","They show how repairs let people use items again.","They show that all broken items are toys.","They explain why the sign is orange."],"answer_index":1}
]$reading_detail$::jsonb)
 as q(subject_id text, grade text, difficulty integer, skill text, standard text, prompt text,
 explanation text, xp integer, kind text, payload jsonb, answer jsonb, choices jsonb, answer_index integer)
)
insert into public.questions(subject_id,grade,difficulty,skill,standard,prompt,explanation,xp,kind,payload,answer,choices,answer_index)
select q.subject_id,q.grade,q.difficulty,q.skill,q.standard,q.prompt,q.explanation,q.xp,q.kind,q.payload,q.answer,q.choices,q.answer_index
from incoming q
where not exists(select 1 from public.questions existing where existing.subject_id=q.subject_id and existing.grade=q.grade and existing.prompt=q.prompt and existing.payload is not distinct from q.payload);
